version: 2.1.0.{build}-{branch}

# Windows-1252

environment:
  RUBY_OPTS: -E UTF-8
  LC_ALL: UTF-8
  LANG: UTF-8
  matrix:
    - RUBY_VERSION: 23
    - RUBY_VERSION: 22
    - RUBY_VERSION: 21
    - RUBY_VERSION: 200
    - RUBY_VERSION: 193

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
